export enum Role {
    SUPER_ADMIN = 'SUPER_ADMIN',
    SUPERVISEUR = 'SUPERVISEUR',
    MERCHANDISEUR_MONO = 'MERCHANDISEUR_MONO',
    MERCHANDISEUR_MULTI = 'MERCHANDISEUR_MULTI',
    Admin = "Admin"
  }
